//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  7 2015 21:36:47).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSGestureRecognizer.h>

@interface NSGestureRecognizer (UXKit)
- (void)__stateChange:(id)arg1;
- (void)setGestureDidEndHandler:(CDUnknownBlockType)arg1;
- (void)setGestureDidChangeHandler:(CDUnknownBlockType)arg1;
- (void)setGestureDidBeginHandler:(CDUnknownBlockType)arg1;
@end

