//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  7 2015 21:36:47).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSIndexPath.h>

@interface NSIndexPath (UXTableView)
+ (id)indexPathForRow:(long long)arg1 inSection:(long long)arg2;
@property(readonly, nonatomic) long long row;

// Remaining properties
@property(readonly, nonatomic) long long section;
@end

