//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  7 2015 21:36:47).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UXBarItem.h"

#import "UXKitAppearance-Protocol.h"

@class NSColor, NSString, NSView, UXViewController;

@interface UXBarButtonItem : UXBarItem <UXKitAppearance>

@property(nonatomic, setter=_setWidthConstrainingItem:) __weak UXBarButtonItem *_widthConstrainingItem; // @synthesize _widthConstrainingItem=__widthConstrainingItem;
@property(readonly, nonatomic) long long systemItem; // @synthesize systemItem=_systemItem;
@property(readonly, nonatomic) UXViewController *contentViewController; // @synthesize contentViewController=_contentViewController;
@property(nonatomic) BOOL ignoresMultiClick; // @synthesize ignoresMultiClick=_ignoresMultiClick;
@property(nonatomic) unsigned long long keyEquivalentModifierMask; // @synthesize keyEquivalentModifierMask=_keyEquivalentModifierMask;
@property(retain, nonatomic) NSString *keyEquivalent; // @synthesize keyEquivalent=_keyEquivalent;
@property(retain, nonatomic) NSString *toolTip; // @synthesize toolTip=_toolTip;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(retain, nonatomic) NSView *customView; // @synthesize customView=_customView;
@property(nonatomic) double width; // @synthesize width=_width;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(readonly, nonatomic) NSView *_view;
- (void)_performAction:(id)arg1;
- (id)_viewOfClass:(Class)arg1;
- (void)setImage:(id)arg1;
- (void)setEnabled:(BOOL)arg1;
- (void)setTitle:(id)arg1;
- (void)tintColorDidChange;
@property(nonatomic) long long tintAdjustmentMode; // @synthesize tintAdjustmentMode=_tintAdjustmentMode;
@property(retain, nonatomic) NSColor *tintColor; // @synthesize tintColor=_tintColor;

- (instancetype)initWithStyle:(long long)style target:(id)target action:(SEL)action;
- (instancetype)initWithContentViewController:(__kindof NSViewController *)viewController;
- (instancetype)initWithCustomView:(__kindof NSView *)view;
- (instancetype)initWithBarButtonSystemItem:(long long)systemItem target:(id)target action:(SEL)action;
- (instancetype)initWithTitle:(NSString *)title style:(long long)style target:(id)target action:(SEL)action;
- (instancetype)initWithImage:(NSImage *)image style:(long long)style target:(id)target action:(SEL)action;
@end

