//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  7 2015 21:36:47).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@import Cocoa;

@interface UXCollectionViewLayoutAttributes : NSObject <NSCopying>

@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;

@property(nonatomic) BOOL isPushing; // @synthesize isPushing=_isPushing;
@property(nonatomic) NSRect floatingFrame; // @synthesize floatingFrame=_floatingFrame;

@property(nonatomic) BOOL isFloating; // @synthesize isFloating=_isFloating;
@property(nonatomic) NSInteger zIndex; // @synthesize zIndex=_zIndex;

@property(nonatomic) CGFloat alpha; // @synthesize alpha=_alpha;
@property(nonatomic) NSSize size; // @synthesize size=_size;
@property(nonatomic) NSPoint center; // @synthesize center=_center;

@property(readonly, nonatomic) NSString *representedElementKind; // @synthesize representedElementKind=_representedElementKind;
@property(readonly, nonatomic) unsigned long long representedElementCategory;

@property(nonatomic) NSRect frame; // @synthesize frame=_frame;
@property(nonatomic) NSRect bounds;

@property(nonatomic, getter=isHidden) BOOL hidden;

@end

