//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  7 2015 21:36:47).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@import Cocoa;

#import "UXViewController.h"

#import "UXCollectionViewDataSource-Protocol.h"
#import "UXCollectionViewDelegate-Protocol.h"

@class NSString, UXCollectionView, UXCollectionViewLayout;

@interface UXCollectionViewController : UXViewController <UXCollectionViewDataSource, UXCollectionViewDelegate>

@property(retain, nonatomic) UXCollectionView *collectionView; // @synthesize collectionView=_collectionView;

- (instancetype)initWithCollectionViewLayout:(UXCollectionViewLayout *)layout;

@end

