//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  7 2015 21:36:47).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UXCollectionViewLayout.h"

@import Cocoa;

@class NSDictionary, NSMutableDictionary;

@interface UXCollectionViewFlowLayout : UXCollectionViewLayout

@property(nonatomic) NSEdgeInsets sectionInset; // @synthesize sectionInset=_sectionInset;
@property(nonatomic) NSSize footerReferenceSize; // @synthesize footerReferenceSize=_footerReferenceSize;
@property(nonatomic) NSSize headerReferenceSize; // @synthesize headerReferenceSize=_headerReferenceSize;
@property(nonatomic) NSSize itemSize; // @synthesize itemSize=_itemSize;
@property(nonatomic) CGFloat minimumInteritemSpacing; // @synthesize minimumInteritemSpacing=_interitemSpacing;
@property(nonatomic) CGFloat minimumLineSpacing; // @synthesize minimumLineSpacing=_lineSpacing;
@property(nonatomic) NSInteger scrollDirection;

@end

