//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  7 2015 21:36:47).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UXView.h"

@import Cocoa;

@class NSImage, NSString;

@interface UXImageView : UXView

@property(retain, nonatomic) NSImage *image;

- (instancetype)initWithImage:(NSImage *)image;
- (instancetype)initWithFrame:(NSRect)frameRect;

@end

