//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  7 2015 21:36:47).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@import Cocoa;

#import "UXView.h"

@interface UXLabel : UXView <NSAccessibilityStaticText>

@property(nonatomic, getter=isHighlighted) BOOL highlighted;
@property(retain, nonatomic) NSColor *highlightedTextColor;
@property(nonatomic) NSInteger numberOfLines;
@property(nonatomic) NSSize shadowOffset;
@property(retain, nonatomic) NSColor *shadowColor;
@property(retain, nonatomic) NSColor *textColor;

@property(nonatomic) BOOL selectable;
@property(nonatomic) BOOL centerVertically;
@property(nonatomic) CGFloat preferredMaxLayoutWidth;
@property(nonatomic) NSTextAlignment textAlignment;
@property(nonatomic) NSLineBreakMode lineBreakMode;
@property(copy, nonatomic) NSAttributedString *attributedText;
@property(copy, nonatomic) NSString *text;
@property(retain, nonatomic) NSFont *font;

- (NSSize)intrinsicContentSize;
- (NSSize)sizeThatFits:(NSSize)size;
- (void)sizeToFit;
- (void)setBackgroundColor:(NSColor *)backgroundColor;
- (instancetype)initWithFrame:(NSRect)frameRect;

@end

