//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  7 2015 21:36:47).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UXKit/UXBarItem.h>

@class NSSet;

@interface UXTabBarItem : UXBarItem
{
    NSSet *_possibleTitles;
}

@property(copy, nonatomic) NSSet *possibleTitles; // @synthesize possibleTitles=_possibleTitles;
- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1;

@end

