//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  7 2015 21:36:47).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSArray, NSResponder, NSString, UXNavigationController, UXNavigationItem, UXSourceController, UXTabBarItem, UXView;
@protocol UXLayoutSupport;

@interface UXViewController : NSViewController
{
    UXNavigationItem *_navigationItem;
    UXTabBarItem *_tabBarItem;
    UXViewController *_accessoryViewController;
    NSArray *_accessoryBarItems;
    UXViewController *_toolbarViewController;
    NSArray *_toolbarItems;
    BOOL _hidesBottomBarWhenPushed;
    struct CGSize _ux_preferredContentSize;
    BOOL _viewDidLoad;
    BOOL _ignoreViewController;
    id <UXLayoutSupport> _topLayoutGuide;
    id <UXLayoutSupport> _bottomLayoutGuide;
    BOOL _isEditing;
    BOOL _automaticallyAdjustsScrollViewInsets;
    long long _modalPresentationStyle;
    unsigned long long _edgesForExtendedLayout;
    UXView *_presentedViewControllerContainerView;
}

+ (Class)viewClass;
@property(retain, nonatomic) UXView *presentedViewControllerContainerView; // @synthesize presentedViewControllerContainerView=_presentedViewControllerContainerView;
@property(nonatomic) BOOL automaticallyAdjustsScrollViewInsets; // @synthesize automaticallyAdjustsScrollViewInsets=_automaticallyAdjustsScrollViewInsets;
@property(nonatomic) unsigned long long edgesForExtendedLayout; // @synthesize edgesForExtendedLayout=_edgesForExtendedLayout;
@property(nonatomic) long long modalPresentationStyle; // @synthesize modalPresentationStyle=_modalPresentationStyle;
@property(nonatomic) BOOL isEditing; // @synthesize isEditing=_isEditing;
- (id)menuForEvent:(id)arg1;
- (id)bottomLayoutGuide;
- (id)topLayoutGuide;
- (void)_setupLayoutGuidesForView:(id)arg1;
- (void)didUpdateLayoutGuides;
- (void)invalidateIntrinsicLayoutInsets;
- (struct NSEdgeInsets)intrinsicLayoutInsets;
- (struct CGSize)preferredContentSizeCappedToSize:(struct CGSize)arg1;
@property struct CGSize preferredContentSize;
- (BOOL)_requiresWindowForTransitionPreparation;
- (id)_ancestorViewControllerOfClass:(Class)arg1;
- (void)_animateView:(id)arg1 fromFrame:(struct CGRect)arg2 toFrame:(struct CGRect)arg3;
- (id)transitionCoordinator;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)dismissViewControllerAnimated:(BOOL)arg1 completion:(void (^)())completionHandler;
- (void)presentViewController:(id)arg1 animated:(BOOL)arg2 completion:(void (^)())completionHandler;
@property(readonly, nonatomic) UXViewController *presentedViewController;
- (void)didMoveToParentViewController:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;
- (void)removeFromParentViewController;
- (void)removeChildViewControllerAtIndex:(long long)arg1;
- (void)addChildViewController:(id)arg1;
- (void)windowDidRecalculateKeyViewLoop;
- (void)windowWillRecalculateKeyViewLoop;
- (void)viewDidLiveResize;
- (void)viewWillLiveResize;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)viewUpdateLayer;
- (void)viewDidDisappear;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewWillAppear;
- (void)_sendViewDidLoad;
- (void)loadView;
- (struct CGRect)_defaultInitialFrame;
- (BOOL)acceptsFirstResponder;
- (void)awakeFromNib;
@property(readonly, nonatomic) NSResponder *preferredFirstResponder;
@property(copy) NSString *title;
- (void)setView:(id)arg1;
@property(readonly, nonatomic) UXView *uxView;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)init;
@property(nonatomic) BOOL hidesBottomBarWhenPushed;
- (long long)preferredToolbarPosition;
- (id)toolbarViewController;
- (void)setToolbarViewController:(id)arg1;
- (id)toolbarItems;
- (void)setToolbarItems:(id)arg1 animated:(BOOL)arg2;
- (void)setToolbarItems:(id)arg1;
- (id)accessoryBarItems;
- (void)setAccessoryBarItems:(id)arg1;
- (id)accessoryViewController;
- (void)setAccessoryViewController:(id)arg1;
@property(readonly, nonatomic) UXNavigationItem *navigationItem;
@property(readonly, nonatomic) UXNavigationController *navigationController;
- (id)tabBarController;
- (id)tabBarItem;
- (id)popoverController;
- (void)updateViewConstraints;
@property(readonly, nonatomic) long long interfaceOrientation;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
@property(nonatomic) BOOL hidesSourceListWhenPushed;
- (BOOL)isTransitory;
- (void)setTransitory:(BOOL)arg1;
- (void)willEncodeNavigationDestination:(id)arg1;
- (id)navigationDestination;
- (id)navigationIdentifier;
@property(readonly, nonatomic) UXSourceController *sourceController;

@end

