//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  7 2015 21:36:47).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@import Cocoa;

@class NSString, NSTitlebarAccessoryViewController, NSToolbarItem, UXToolbar, UXViewController, UXNavigationController;

@interface UXWindowController : NSWindowController <NSToolbarDelegate, NSWindowDelegate>
{
    NSTitlebarAccessoryViewController *_titlebarAccessoryViewController;
    UXToolbar *_currentAccessoryToolbar;
    NSToolbarItem *_navigationBarToolbarItem;
}

+ (id)defaultWindow;
@property __weak NSToolbarItem *navigationBarToolbarItem; // @synthesize navigationBarToolbarItem=_navigationBarToolbarItem;
- (void)windowDidBecomeFirstResponder:(id)arg1;
- (void)windowDidRecalculateKeyViewLoop:(id)arg1;
- (void)windowWillRecalculateKeyViewLoop:(id)arg1;
- (void)windowWillExitFullScreen:(id)arg1;
- (void)windowWillEnterFullScreen:(id)arg1;
- (void)setWindow:(NSWindow *)window;
- (UXNavigationController *)rootNavigationController;
@property(retain, nonatomic) UXViewController *rootViewController;
- (id)initWithWindow:(NSWindow *)window;
- (id)initWithRootViewController:(UXViewController *)rootViewController;

@end

